name: ❓ Support Request
description: Get help when you encounter problems with Homebridge software. Or simply ask a question.

labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Hi. Before you start filling out this form be aware of the following points:
        - Review our **Troubleshooting** and **FAQ** pages in the Wiki to ensure your issue isn't already solved by those steps.
        - Search through **existing issues** (resolved or open) which might provide a solution to your problem already.
        - If your issue is **plugin specific**, raise an issue with the plugin author on their GitHub page instead.
        - **Ask the community**: We have a Discord and a Reddit. Active community members might provide help quicker on those platforms.

  - type: textarea
    id: problem
    attributes:
      label: Current Situation
      description: Please provide an overview of the current situation and illustrate potential problems or shortcomings.
      placeholder: A clear and concise description of the problem or situation that should be addressed.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide relevant log output.
        Be sure to **remove any sensitive information** (passwords, tokens, etc.).
        If you have a lengthy log message, please use the file upload functionality in the `Additional Context` section to supply log files.
      placeholder: Please paste logging output. Refer to the GitHub Wiki on how to enable `DEBUG` output.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please provide, if applicable, the content of your configuration files (e.g. `config.json`).
        Be sure to **remove any sensitive information** (passwords, tokens, etc.).
        If you have a lengthy configuration, please use the file upload functionality in the `Additional Context` section to supply config files.
      placeholder: Please paste configuration ...
      render: json
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe your Environment when running Homebridge software.
        It should include Operating System version, runtime version and the version of the software itself.

        The environment description might look like the following:
          - **OS**: Ubuntu 20.04
          - **Homebridge**: 1.3.6
          - **Node**: 16.13.0 (output of `node -v`)
          - **npm**: 8.1.0 (output of `npm -v`)
      value: |
        - OS:
        - Software:
        - Node:
        - npm:
    validations:
      required: true

  - type: dropdown
    id: process-supervisor
    attributes:
      label: Process Supervisor
      description: Which supervisor do you use to run Homebridge Software.
      options:
        - hb-service
        - Docker (Mention image name in `Additional Context`)
        - systemd
        - init-d
        - launchctl
        - pm2
        - other (Explain in `Additional Context`)
        - not applicable
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Please provide any additional context that might be relevant for your request.

        It might include screenshots, configuration (files) or log output.
      placeholder: Any additional context that might be relevant for your request.
