name: Lint TypeDoc

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Defines the node version setup'
        default: 16
        required: false
        type: number

jobs:
  eslint:
    name: Lint TypeDoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: eslint
        run: npm run lint-docs --if-present
        env:
          CI: true
