name: PR Labeler

on:
  workflow_call:
    secrets:
      token:
        description: 'The GitHub Token'
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
